=== Adizbek/web-types/schema/src/web-types.schema.json
{
  "$id": "",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "web-types",
  "type": "object",
  "properties": {
    "framework": {
      "type": "string",
      "enum": [
        "vue"
      ]
    },
    "name": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "contributions": {
      "type": "object",
      "properties": {
        "html": {
          "$ref": "#/definitions/html"
        }
      }
    }
  },
  "required": [
    "framework",
    "name",
    "version",
    "contributions"
  ],
  "definitions": {
    "named-entity": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "doc-url": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "typed-entity": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/named-entity"
        }
      ],
      "properties": {
        "type": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      }
    },
    "html": {
      "type": "object",
      "properties": {
        "types-syntax": {
          "type": "string",
          "enum": [
            "typescript"
          ]
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/html-tag"
          }
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/html-attribute"
          }
        }
      }
    },
    "html-tag": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/named-entity"
        }
      ],
      "properties": {
        "source-file": {
          "type": "string"
        },
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/html-tag-attribute"
          }
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/html-tag-event"
          }
        },
        "slots": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/named-entity"
          }
        },
        "vue-scoped-slots": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/html-tag-vue-scoped-slot"
          }
        },
        "vue-model": {
          "$ref": "#/definitions/html-tag-vue-model"
        }
      }
    },
    "html-attribute": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/typed-entity"
        }
      ],
      "properties": {
        "source-file": {
          "type": "string"
        }
      }
    },
    "html-tag-attribute": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/typed-entity"
        }
      ],
      "properties": {
        "default": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "html-tag-event": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/named-entity"
        }
      ],
      "properties": {
        "arguments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/typed-entity"
          }
        }
      }
    },
    "html-tag-vue-scoped-slot": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/named-entity"
        }
      ],
      "properties": {
        "properties": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/typed-entity"
          }
        }
      }
    },
    "html-tag-vue-model": {
      "type": "object",
      "properties": {
        "prop": {
          "type": "string"
        },
        "event": {
          "type": "string"
        }
      }
    }
  }
}

=== Adizbek/web-types/packages/vue/vue@2.1.8.web-types.json
{
  "$schema": "../../schema/web-types.schema.json",
  "framework": "vue",
  "name": "vue",
  "version": "2.1.8",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "tags": [
        {
          "name": "KeepAlive",
          "source-file": "./node_modules/vue/dist/vue.runtime.common.js",
          "attributes": [
            {
              "name": "exclude"
            },
            {
              "name": "include"
            }
          ],
          "slots": [
            {
              "name": "default"
            }
          ]
        },
        {
          "name": "Transition",
          "source-file": "./node_modules/vue/dist/vue.runtime.common.js",
          "attributes": [
            {
              "name": "appear"
            },
            {
              "name": "appearActiveClass"
            },
            {
              "name": "appearClass"
            },
            {
              "name": "appearToClass"
            },
            {
              "name": "css"
            },
            {
              "name": "enterActiveClass"
            },
            {
              "name": "enterClass"
            },
            {
              "name": "enterToClass"
            },
            {
              "name": "leaveActiveClass"
            },
            {
              "name": "leaveClass"
            },
            {
              "name": "leaveToClass"
            },
            {
              "name": "mode"
            },
            {
              "name": "name"
            },
            {
              "name": "type"
            }
          ],
          "slots": [
            {
              "name": "default"
            }
          ]
        },
        {
          "name": "TransitionGroup",
          "source-file": "./node_modules/vue/dist/vue.runtime.common.js",
          "attributes": [
            {
              "name": "appear"
            },
            {
              "name": "appearActiveClass"
            },
            {
              "name": "appearClass"
            },
            {
              "name": "appearToClass"
            },
            {
              "name": "css"
            },
            {
              "name": "enterActiveClass"
            },
            {
              "name": "enterClass"
            },
            {
              "name": "enterToClass"
            },
            {
              "name": "leaveActiveClass"
            },
            {
              "name": "leaveClass"
            },
            {
              "name": "leaveToClass"
            },
            {
              "name": "moveClass"
            },
            {
              "name": "name"
            },
            {
              "name": "tag"
            },
            {
              "name": "type"
            }
          ],
          "slots": [
            {
              "name": "default"
            }
          ]
        }
      ],
      "attributes": [
        {
          "name": "v-model"
        },
        {
          "name": "v-show",
          "source-file": "./node_modules/vue/dist/vue.runtime.common.js"
        }
      ]
    }
  }
}

=== Adizbek/web-types/packages/vue-router/vue-router@3.1.0.web-types.json
{
  "$schema": "../../schema/web-types.json",
  "name": "vue-router",
  "version": "3.1.0",
  "framework": "vue",
  "contributions": {
    "html": {
      "description-markup": "markdown",
      "types-syntax": "typescript",
      "tags": [
        {
          "name": "RouterLink",
          "doc-url": "https://router.vuejs.org/api/#to",
          "description": "`<router-link>` is the component for enabling user navigation in a router-enabled app. The target location is specified with the `to` prop. It renders as an `<a>` tag with correct `href` by default, but can be configured with the `tag` prop. In addition, the link automatically gets an active CSS class when the target route is active.",
          "attributes": [
            {
              "name": "to",
              "required": true,
              "doc-url": "https://router.vuejs.org/api/#to",
              "description": "Denotes the target route of the link. When clicked, the value of the `to` prop will be passed to `router.push()` internally, so the value can be either a string or a location descriptor object.",
              "value": {
                "kind": "expression",
                "type": [
                  "string",
                  "object"
                ]
              }
            },
            {
              "name": "tag",
              "value": {
                "kind": "expression",
                "type": "string"
              },
              "default": "'a'",
              "doc-url": "https://router.vuejs.org/api/#tag",
              "description": "Sometimes we want `<router-link>` to render as another tag, e.g `<li>`. Then we can use `tag` prop to specify which tag to render to, and it will still listen to click events for navigation."
            },
            {
              "name": "exact",
              "value": {
                "kind": "expression",
                "type": "boolean"
              },
              "default": "false",
              "doc-url": "https://router.vuejs.org/api/#exact",
              "description": "The default active class matching behavior is **inclusive match**. For example, `<router-link to=\"/a\">` will get this class applied as long as the current path starts with `/a/` or is `/a`.\n\nOne consequence of this is that `<router-link to=\"/\">` will be active for every route! To force the link into \"exact match mode\", use the `exact` prop"
            },
            {
              "name": "append",
              "value": {
                "kind": "expression",
                "type": "boolean"
              },
              "default": "false",
              "doc-url": "https://router.vuejs.org/api/#append",
              "description": "Setting `append` prop always appends the relative path to the current path. "
            },
            {
              "name": "replace",
              "value": {
                "kind": "expression",
                "type": "boolean"
              },
              "default": "false",
              "doc-url": "https://router.vuejs.org/api/#replace",
              "description": "Setting `replace` prop will call `router.replace()` instead of `router.push()` when clicked, so the navigation will not leave a history record."
            },
            {
              "name": "activeClass",
              "value": {
                "kind": "expression",
                "type": "string"
              },
              "default": "'router-link-active'",
              "doc-url": "https://router.vuejs.org/api/#active-class",
              "description": "Configure the active CSS class applied when the link is active. Note the default value can also be configured globally via the `linkActiveClass` router constructor option."
            },
            {
              "name": "exactActiveClass",
              "value": {
                "kind": "expression",
                "type": "string"
              },
              "default": "'router-link-exact-active'",
              "doc-url": "https://router.vuejs.org/api/#exact-active-class",
              "description": "Configure the active CSS class applied when the link is active with exact match. Note the default value can also be configured globally via the `linkExactActiveClass` router constructor option."
            },
            {
              "name": "ariaCurrentValue",
              "value": {
                "kind": "expression",
                "type": "'page' | 'step' | 'location' | 'date' | 'time'"
              },
              "default": "'page'",
              "doc-url": "https://router.vuejs.org/api/#aria-current-value",
              "description": "Configure the value of `aria-current` when the link is active with exact match. It must be one of the allowed values for aria-current in the ARIA spec. In most cases, the default of `page` should be the best fit."
            },
            {
              "name": "event",
              "value": {
                "kind": "expression",
                "type": [
                  "string",
                  "string[]"
                ]
              },
              "default": "'click'",
              "doc-url": "https://router.vuejs.org/api/#event",
              "description": "Specify the event(s) that can trigger the link navigation."
            }
          ],
          "slots": [
            {
              "name": "default",
              "vue-properties": [
                {
                  "name": "href",
                  "description": "Resolved url. This would be the `href` attribute of an `a` element",
                  "type": "string"
                },
                {
                  "name": "route",
                  "description": "Resolved normalized location",
                  "type": "object"
                },
                {
                  "name": "navigate",
                  "description": "Function to trigger the navigation. **It will automatically prevent events when necessary**, the same way `router-link` does",
                  "type": "() => any"
                },
                {
                  "name": "isActive",
                  "description": "`true` if the active class should be applied. Allows to apply an arbitrary class",
                  "type": "boolean"
                },
                {
                  "name": "isExactActive",
                  "description": "`true` if the exact active class should be applied. Allows to apply an arbitrary class",
                  "type": "boolean"
                }
              ]
            }
          ]
        },
        {
          "name": "RouterView",
          "doc-url": "https://router.vuejs.org/api/#router-view",
          "description": "The `<router-view>` component is a functional component that renders the matched component for the given path. Components rendered in `<router-view>` can also contain their own `<router-view>`, which will render components for nested paths.",
          "attributes": [
            {
              "name": "name",
              "value": {
                "kind": "expression",
                "type": "string"
              },
              "default": "'default'",
              "doc-url": "https://router.vuejs.org/api/#name",
              "description": "When a `<router-view>` has a name, it will render the component with the corresponding name in the matched route record's components option. See Named Views for an example."
            }
          ]
        }
      ]
    }
  }
}

=== Adizbek/web-types/packages/vue/vue@1.0.0.web-types.json
{
  "$schema": "../../schema/web-types.json",
  "framework": "vue",
  "name": "vue",
  "version": "1.0.0",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "tags": [
        {
          "name": "Component",
          "doc-url": "https://v1.vuejs.org/api/#component",
          "description": "Alternative syntax for invoking components. Primarily used for dynamic components with the `is` attribute.",
          "attributes": [
            {
              "name": "is"
            },
            {
              "name": "keep-alive",
              "value": {
                "kind": "expression",
                "type": "boolean"
              },
              "type": "boolean"
            },
            {
              "name": "transition-mode"
            }
          ]
        },
        {
          "name": "Slot",
          "doc-url": "https://v1.vuejs.org/api/#slot",
          "description": "`<slot>` elements serve as content distribution outlets in component templates. The slot element itself will be replaced.\nA slot with the `name` attribute is called a named slot. A named slot will distribute content with a `slot` attribute that matches its name.",
          "attributes": [
            {
              "name": "name",
              "value": {
                "kind": "expression",
                "type": "string"
              }
            }
          ]
        },
        {
          "name": "Partial",
          "doc-url": "https://v1.vuejs.org/api/#partial",
          "description": "`<partial>` elements serve as outlets for registered template partials. Partial contents are also compiled by Vue when inserted. The `<partial>` element itself will be replaced. It requires a `name` attribute which will be used to resolve the partialâ€™s content.",
          "attributes": [
            {
              "name": "name",
              "required": true
            }
          ]
        }
      ],
      "attributes": [
        {
          "name": "v-bind"
        },
        {
          "name": "v-cloak"
        },
        {
          "name": "v-el",
          "source": {
            "file": "src/directives/public/el.js",
            "offset": 0
          }
        },
        {
          "name": "v-for",
          "source": {
            "file": "src/directives/public/for.js",
            "offset": 0
          }
        },
        {
          "name": "v-html"
        },
        {
          "name": "v-if",
          "source": {
            "file": "src/directives/public/if.js",
            "offset": 0
          }
        },
        {
          "name": "v-model",
          "source": {
            "file": "src/directives/public/model/index.js",
            "offset": 0
          }
        },
        {
          "name": "v-on",
          "source": {
            "file": "src/directives/public/on.js",
            "offset": 0
          }
        },
        {
          "name": "v-ref"
        },
        {
          "name": "v-show"
        },
        {
          "name": "v-text"
        }
      ]
    }
  }
}

=== Adizbek/web-types/packages/vue-client-only/vue-client-only@2.0.0.web-types.json
{
  "$schema": "../../schema/web-types.json",
  "name": "vue-client-only",
  "version": "2.0.0",
  "framework": "vue",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "description-markup": "markdown",
      "tags": [
        {
          "name": "client-only",
          "description": "This component is used to purposely render a component only on client-side. To import a component only on the client, register the component in a client-side only plugin.",
          "doc-url": "https://github.com/egoist/vue-client-only/blob/master/README.md",
          "attributes": [
            {
              "name": "placeholder",
              "description": "Use a text as placeholder until `<client-only />` is mounted on client-side."
            }
          ],
          "slots": [
            {
              "name": "placeholder",
              "description": "Use a slot as placeholder until `<client-only />` is mounted on client-side."
            }
          ]
        }
      ]
    }
  }
}

=== Adizbek/web-types/packages/vue/vue@2.0.0.web-types.json
{
  "$schema": "../../schema/web-types.schema.json",
  "framework": "vue",
  "name": "vue",
  "version": "2.0.0",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "tags": [
        {
          "name": "KeepAlive"
        },
        {
          "name": "Transition",
          "source-file": "./node_modules/vue/dist/vue.common.js",
          "attributes": [
            {
              "name": "appear"
            },
            {
              "name": "appearActiveClass"
            },
            {
              "name": "appearClass"
            },
            {
              "name": "css"
            },
            {
              "name": "enterActiveClass"
            },
            {
              "name": "enterClass"
            },
            {
              "name": "leaveActiveClass"
            },
            {
              "name": "leaveClass"
            },
            {
              "name": "mode"
            },
            {
              "name": "name"
            },
            {
              "name": "type"
            }
          ],
          "slots": [
            {
              "name": "default"
            }
          ]
        },
        {
          "name": "TransitionGroup",
          "source-file": "./node_modules/vue/dist/vue.common.js",
          "attributes": [
            {
              "name": "appear"
            },
            {
              "name": "appearActiveClass"
            },
            {
              "name": "appearClass"
            },
            {
              "name": "css"
            },
            {
              "name": "enterActiveClass"
            },
            {
              "name": "enterClass"
            },
            {
              "name": "leaveActiveClass"
            },
            {
              "name": "leaveClass"
            },
            {
              "name": "moveClass"
            },
            {
              "name": "name"
            },
            {
              "name": "tag"
            },
            {
              "name": "type"
            }
          ],
          "slots": [
            {
              "name": "default"
            }
          ]
        }
      ],
      "attributes": [
        {
          "name": "v-model"
        },
        {
          "name": "v-show"
        }
      ]
    }
  }
}

=== Adizbek/web-types/packages/vue-no-ssr/vue-no-ssr@1.0.0.web-types.json
{
  "$schema": "../../schema/web-types.json",
  "name": "vue-no-ssr",
  "version": "1.0.0",
  "framework": "vue",
  "contributions": {
    "html": {
      "types-syntax": "typescript",
      "description-markup": "markdown",
      "tags": [
        {
          "name": "no-ssr",
          "description": "This component is used to purposely render a component only on client-side. To import a component only on the client, register the component in a client-side only plugin.",
          "doc-url": "https://github.com/egoist/vue-client-only/blob/1.x/README.md",
          "attributes": [
            {
              "name": "placeholder",
              "description": "Use a text as placeholder until `<no-ssr />` is mounted on client-side."
            }
          ],
          "slots": [
            {
              "name": "placeholder",
              "description": "Use a slot as placeholder until `<no-ssr />` is mounted on client-side."
            }
          ]
        }
      ]
    }
  }
}
